### PR TITLE
Bitcoind main loop

### PR DESCRIPTION
**Pull request by darosior**
This implements the main actions on the `bitcoind` side, and as such begins the actual wallet logic. Pretty basic for now: we poll `listunspent` to stay in sync in `bitcoind`, cry blood because we have to maintain a map from address to derivation (see commit messages), and store / load deposits in the database.

We poll in the main thread, but we'll surely use a more elaborated event loop soon :)

Now going to unit test the DB and start the JSONRPC interface: hand-testing isn't going to last and we need a functional testing framework (wanted to reuse https://github.com/re-vault/revault-demo/tree/master/tests btw).

### CODE REVIEW

**Comment by darosior** [comment]
Use FromHex https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/hex.rs instead of my boutique function ! (Thanks Ed)

**Comment by darosior** [comment]
A lot of stuff that i'd like to rework but i have to stop shaving yawks at some point. Will focus on the JSONRPC integration tomorrow.

**Comment by darosior** [comment]
Rebased on top of #13 and added a test for deposits management in db.

**Comment by edouardparis** [comment]
ACK 1a896f810e46f1d113fb8d9713353eb6e16b185d

**Pull request merged**
