### PR TITLE
rpc: don't overwrite buffer when reading from stream

### PR DESCRIPTION
**Pull request by darosior**
Unfortunately i don't have the time to add a test rn, but we should have hardened that..

### CODE REVIEW

**Comment by edouardparis** [comment]
Please change fn arguments for:
```diff
-fn read_bytes_from_stream(mut stream: &UnixStream) -> Result<Option<Vec<u8>>, io::Error> {
+fn read_bytes_from_stream(stream: &mut dyn io::Read) -> Result<Option<Vec<u8>>, io::Error> {
```
and add unit test:

```rust
    use super::read_bytes_from_stream;
    use std::io::Cursor;
    #[test]
    fn read_bytes_from_stream_test() {
        let data = vec![1; 522];
        let mut stream = Cursor::new(data.clone());
        let res = read_bytes_from_stream(&mut stream);
        assert_eq!(res.unwrap().unwrap(), data);
    }
```

**Comment by darosior** [comment]
Thanks! Will improve over the unit test now that you mainly wrote it :)

**Comment by darosior** [comment]
Finally got to adding it. We'll improve it later, for now i need to PR the signature sharing :)

**Comment by darosior** [comment]
ACK 3403758

**Pull request merged**
