### PR TITLE
Documentation boilerplate

### PR DESCRIPTION
**Pull request by darosior**
A license, README, and COnTRIBUTING.

### CODE REVIEW

**Comment by darosior** [comment]
Of course the CI fails as there is no code yet

**Review by edouardparis — APPROVED** [review]
good start, we need to give information for security disclosure

**Comment by darosior** [comment]
Yeah, probably ok to accept issues for at least 9M.

-------- Original Message --------

**Comment by darosior** [comment]
self-ACK 7cb94e8

**Pull request merged**
